description = "Markdownを簡素化してスライドを生成"
prompt = """
## Context
- ガイドライン: [rules/slide_rules.md](rules/slide_rules.md)
- テンプレート: [template.md](template.md)
- 入力ファイル: [input/*.md](input/*.md)

## タスク
1. 入力Markdownファイルを読む。
2. スライドガイドラインを読む。
3. ガイドラインに従いMarkdownを簡素化（冗長削除 / 要約 / 箇条書き最適化 / 1スライド1主題）。
4. テンプレートを読む。
5. 必須front-matter補完しテンプレート適用。`---` でページ区切り調整。
6. 中間結果を `artifact/slides.md` に保存。
"""