description = "報告の概要、骨子を読んで、スライドを生成する"
prompt = """
## Context
- [報告の概要、骨子](artifact/*.md)
- [ガイドライン](guidance/slide_rules.md)
- [テンプレート](template.md)

## タスク
1. 報告の概要、骨子を読む。
2. ガイドラインを読む。
3. ガイドラインに従って報告用スライドを生成する。
4. テンプレートを読む。
5. テンプレートに従ってスライドを構成する。(Marpで出力するために必要なfront-matterはテンプレートに含まれる)
6. ファイル (`output/slides.md`) に保存する。
"""